# Configuração do Render para Digimon Evolution
services:
  # API Backend
  - type: web
    name: digimon-evolution-api
    env: docker
    dockerfilePath: ./deploy/Dockerfile.api
    dockerContext: ./digimon-api
    plan: starter
    region: oregon
    branch: main
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: HOST
        value: 0.0.0.0
      - key: SUPABASE_URL
        fromDatabase:
          name: digimon-supabase
          property: connectionString
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: CORS_ORIGIN
        value: https://digimon-evolution-frontend.onrender.com
      - key: RATE_LIMIT_MAX
        value: 100
      - key: RATE_LIMIT_WINDOW
        value: 60000
      - key: LOG_LEVEL
        value: info

  # Frontend React
  - type: web
    name: digimon-evolution-frontend
    env: docker
    dockerfilePath: ./deploy/Dockerfile.frontend
    dockerContext: ./digimon-frontend
    plan: starter
    region: oregon
    branch: main
    buildCommand: |
      docker build \
        --build-arg VITE_API_URL=https://digimon-evolution-api.onrender.com \
        -t frontend .
    envVars:
      - key: VITE_API_URL
        value: https://digimon-evolution-api.onrender.com

databases:
  - name: digimon-supabase
    databaseName: postgres
    user: postgres
    plan: starter
    region: oregon
